library("xml2")
ls("package:xml2")
xml<-read_xml("C:/lUsers/oppos/Downloads/Students.xml")
print(xml)
library("readr")
csv<-read_csv("C:/Users/oppos/Downloads/retail_data.csv")
print(csv)
colnames(csv)
dim(csv)
mean(csv$Age)
y<-na.omit(csv$Age)
mean(y)
str(csv)
colnames(csv)
rownames(csv)
dim(csv)
str(csv)
sum(is.na(csv$Age))

colSums(is.na(csv))
summary(csv$Age)
# hist(csv$Age)
# hist(csv$Name)
csv$doubleage<-(csv$Age*2)
print(doubleage)
dim(csv)
View(csv)
write_csv(csv,"C:/Users/oppos/Downloads/demo.csv", col_names=TRUE)